### ISSUE TITLE
Remote Digest url

### ISSUE THREAD

**Issue by k3oni** [engineerapart/TheRemoteFreelancer#18]
Check the url for Remote Digest, nothing there right now just a default GoDaddy page.

**Comment by G07cha** [comment]
@k3oni is there should be a link to Remote Digest's facebook group?
BTW: In the group, they also use this link.

**Comment by k3oni** [comment]
@G07cha Might be better to just use the Facebook group url as there you can sign up for the newsletter. The current URL doesn't help with anything as it's just a Godaddy placeholder.

**Comment by CodinRonan** [comment]
@k3oni @G07cha it's weird, even when I go to their FB page I see this:

https://www.facebook.com/RemoteDigest/

Nothing since February 2015? I must be missing something.

I removed the URL for now, is there another URL that goes somewhere useful?

**Comment by danse** [comment]
I can't find anything related to this "Remote Digest"

**Comment by andychase** [comment]
I checked all the links and removed the ones that are offline (Just codegolphers from #63 and "Freelance per hour")
