### ISSUE TITLE
Similar list

### ISSUE THREAD

**Issue by karllhughes** [engineerapart/TheRemoteFreelancer#31]
I don't know if you've seen this list https://github.com/lukasz-madon/awesome-remote-job#job-boards

But there's a lot of crossover with what @lukasz-madon is doing.

**Comment by lukasz-madon** [comment]
True. Although my list is more optimized for full-time positions and companies.

**Comment by danse** [comment]
Right, and it's great to have a different list more focused on freelancing. What makes Upwork attractive is the flexibility it offers, which is not accepted by many employers

**Comment by andychase** [comment]
I agree with @danse though it might make sense to incorporate a link to that
