### ISSUE TITLE
remotecoder.io and remotedigest.com sites are unavailable to access

### ISSUE THREAD

**Issue by ysupr** [engineerapart/TheRemoteFreelancer#47]
both site are unavailable. while remotecoder.io showing that it is on hiberation mode, undergoing refurbishment, and remotecoder just showing white blank. 
.
.
or it just me?

**Comment by CodinRonan** [comment]
Weird, I visited both before adding them. I'll remove them here in a little bit, thanks for noticing!

**Comment by CodinRonan** [comment]
Nope def gone, removed!
