### ISSUE TITLE
hacker news monthly job postings?

### ISSUE THREAD

**Issue by seiyria** [engineerapart/TheRemoteFreelancer#52]
not sure how you'd incorporate it, but these are a fairly decent source too

**Comment by danse** [comment]
even though often they don't accept people from remote, and they ask for full time. Also, this list is all made of links, so yeah that wouldn't be easy to incorporate

**Comment by seiyria** [comment]
I've actually found a few remote contracts there (since that's all I look for), but yes, it is tough to incorporate, unless you could add a search query that shows all of them when linked. I don't know how to use HN that well so I don't even know if that's possible.

**Comment by andychase** [comment]
There's these tools that could be linked: 

http://hnhiring.me/

https://hnjobs.emilburzo.com/

It might make more sense to have a separate section that's just "open job boards".

**Comment by chrisallenlane** [comment]
> It might make more sense to have a separate section that's just "open job boards".

+1. I wasn't aware that HN even _had_ a job board, despite reading it daily. A listing of high-quality job boards would be very helpful.

**Comment by danse** [comment]
I vote for http://hnhiring.me because there it's easier to understand what's about and to follow the link to the original post
