### ISSUE TITLE
Remove Pipeline from this list

### ISSUE THREAD

**Issue by timsvoice** [engineerapart/TheRemoteFreelancer#56]
Pipeline mostly focuses on PHP and Wordpress, which is fine. But after I attempted to contact them through their website, email, and also twitter, to cancel my subscription, I did not receive a response on any channel.

I now have to call my CC company and dispute the charge. They are a poor business and should be removed from this list.

**Comment by codinronan** [comment]
@timsvoice Wow that's terrible, thank you for the note, I will remove them ASAP

**Comment by timsvoice** [comment]
Thanks! Just don't want someone else to have to go through the same thing.

**Comment by codinronan** [comment]
@timsvoice definitely, and, done :)
