### ISSUE TITLE
X-Team?!

### ISSUE THREAD

**Issue by seancafferky** [engineerapart/TheRemoteFreelancer#60]
X-Team is not a marketplace or job listing resource.

If you're going to include X-Team, you'd need to consider adding any of the other 90,000 "hire our anonymous team!" outsourcing companies.

(Thank you for the otherwise helpful list.)

**Comment by andychase** [comment]
Maybe we should sort these into a separate section? It does seem like it would still be beneficial to list these for people looking for remote work.

**Comment by andychase** [comment]
It's now its own list and clearly marked as such. Let me know if there's better agencies to list.
