### ISSUE TITLE
Already a list at http://alternativeto.net/

### ISSUE THREAD

**Issue by streger** [engineerapart/TheRemoteFreelancer#7]
http://alternativeto.net/software/upwork/

**Comment by lwm** [comment]
Also https://github.com/lukasz-madon/awesome-remote-job.

Why duplicate efforts? Join an existing attempt and make it better!

**Comment by CodinRonan** [comment]
@streger @lwm nice. I'll see what I can do there. alternativeto is a nice short list, not really community maintained though.

**Comment by streger** [comment]
@CodinRonan it is, the main tagline of alternativeto.net is _Crowdsourced software recommendations_.
