### ISSUE TITLE
No license doesn't imply permission to use and modify

### ISSUE THREAD

**Issue by mrzool** [engineerapart/TheRemoteFreelancer#9]
Just FYI, if you don't make your license terms explicit your work [defaults to full copyright](https://en.wikipedia.org/wiki/License-free_software). That's why people include licenses that explicitly put their work in the public domain and give permissions to copy, modify and republish. No huge deal in this case, I just wanted to let you know since you seem to assume the opposite in the readme.

**Comment by lwm** [comment]
Wow. Didn't know that. Thanks.

**Comment by tricoder42** [comment]
Use [CC-BY](https://creativecommons.org/licenses/by/4.0/) if you don't care.  Or [WTFPL](http://www.wtfpl.net/) if you really don't care 😄

**Comment by taralx** [comment]
Please don't use WTFPL. It doesn't protect your contributors.

**Comment by RyanZim** [comment]
If you really, really, don't care, use CC0.

> Please don't use WTFPL

:+1:

**Comment by RyanZim** [comment]
Oops, this does have a license now: https://github.com/engineerapart/TheRemoteFreelancer/blob/master/LICENSE. @mrzool Can you close?

**Comment by CodinRonan** [comment]
@ryanchartrand @mrzool is the one I added sufficient? I don't have strong feelings one way or the other; if you do I am happy to change it.

**Comment by mrzool** [comment]
As already said above and [elsewhere](https://news.ycombinator.com/item?id=12777598), a Creative Common license would probably be a better fit, as the Unlicense is made for software. That's your call to make though, go with whatever makes more sense for you.

**Comment by badorg** [comment]
This is no Problem,understanding is hart.
Am 02.11.2016 14:03 schrieb "Mattia Tezzele" <notifications@github.com>:
